import React from "react";

const playlists=[
        {
            id:1,
            nome:'ArRahuman',
            capa:'Nadhiye Nadhiye',
            artista:'Muthu',
            musicas:[
                {
                    id:10,
                    nome:'kajsn',
                    arquivo:'Anirudh.mp3'
                },
                {
                    id:12,
                    nome:'laksc',
                    arquivo:'ArRahuman.mp3'
                },
                {
                    id:13,
                    nome:'lkmj',
                    arquivo:'joker.mp3'
                }
            ]
        },
        {
            id:2,
            nome:'ArRahuman',
            capa:'Nadhiye Nadhiye',
            artista:'Muthu',
            musicas:[
                {
                    id:14,
                    nome:'kajsn',
                    arquivo:'Anirudh.mp3'
                },
                {
                    id:15,
                    nome:'laksc',
                    arquivo:'ArRahuman.mp3'
                },
                {
                    id:16,
                    nome:'lkmj',
                    arquivo:'joker.mp3'
                }
            ]
        },
        {
            id:3,
            nome:'ArRahuman',
            capa:'Nadhiye Nadhiye',
            artista:'Muthu',
            musicas:[
                {
                    id:17,
                    nome:'kajsn',
                    arquivo:'Anirudh.mp3'
                },
                {
                    id:18,
                    nome:'laksc',
                    arquivo:'ArRahuman.mp3'
                },
                {
                    id:19,
                    nome:'lkmj',
                    arquivo:'joker.mp3'
                }
            ]
        },
        {
            id:4,
            nome:'ArRahuman',
            capa:'Nadhiye Nadhiye',
            artista:'Muthu',
            musicas:[
                {
                    id:20,
                    nome:'kajsn',
                    arquivo:'Anirudh.mp3'
                },
                {
                    id:21,
                    nome:'laksc',
                    arquivo:'ArRahuman.mp3'
                },
                {
                    id:22,
                    nome:'lkmj',
                    arquivo:'joker.mp3'
                }
            ]
        },
        {
            id:5,
            nome:'ArRahuman',
            capa:'Nadhiye Nadhiye',
            artista:'Muthu',
            musicas:[
                {
                    id:23,
                    nome:'kajsn',
                    arquivo:'Anirudh.mp3'
                },
                {
                    id:24,
                    nome:'laksc',
                    arquivo:'ArRahuman.mp3'
                },
                {
                    id:25,
                    nome:'lkmj',
                    arquivo:'joker.mp3'
                }
            ]
        },
        {
            id:6,
            nome:'ArRahuman',
            capa:'Nadhiye Nadhiye',
            artista:'Muthu',
            musicas:[
                {
                    id:26,
                    nome:'kajsn',
                    arquivo:'Anirudh.mp3'
                },
                {
                    id:27,
                    nome:'laksc',
                    arquivo:'ArRahuman.mp3'
                },
                {
                    id:28,
                    nome:'lkmj',
                    arquivo:'joker.mp3'
                }
            ]
        }
            
]

export default playlists;